resources:
- ../../base

namespace: prod

patches:
- path: replicas.yaml


configMapGenerator:
- envs:
  - config.properties
  name: mywebapp-configmapv1.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
