resources:
- deployment.yaml
- service.yaml


commonAnnotations:
  app: mywebapp-annotation

nameSuffix: -v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: mywebapp
